[project]
name = "nasa-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.9.4",
    "notebook>=7.4.3",
    "python-dotenv>=1.1.0",
    "requests>=2.32.4",
]
